### PR TITLE
Add DYN_TEST_BASENAME for -V/-h

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Going to do this with dbg too .. please sync this to mkiocccentry if you can. Thanks.

**Review by lcn2 — APPROVED** [review]
basename(thank/you/@xexyl) 🤓

**Comment by xexyl** [comment]
> basename(thank/you/@xexyl) 🤓

```diff
1c1,7
< basename(thank/you/@xexyl) 🤓
---
> #include <libgen.h>
> #include <stdio.h>
>
> int main(void)
> {
>     printf("%s\n",basename("thank/you/@xexyl) 🤓"));
> }
```

:-)

**Comment by xexyl** [comment]
... or, if you prefer:

```diff
1c1,7
< basename(thank/you/@xexyl) 🤓
---
> #include <libgen.h>
> #include <stdio.h>
> 
> int main(void)
> {
>     printf("%s\n",basename("thank/you/@xexyl"));/* 🤓*/
> }
```

**Pull request merged**
