### PR TITLE
Add CodeQL and test workflows

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I must leave ... feel free to add anything I missed. I can do this for dbg tomorrow. Good day!

**Review by lcn2 — APPROVED** [review]
Thank you @xexyl.

Please consider doing this for the dbg repo too.

**Comment by xexyl** [comment]
> Thank you @xexyl.
> 
> 
> 
> Please consider doing this for the dbg repo too.

Was already planning it. Remind me if I do not do it soon.

**Comment by lcn2** [comment]
Hello @xexyl,

The [.github/workflows/codeql.yml](https://github.com/lcn2/dyn_array/blob/master/.github/workflows/codeql.yml) you contributed to this repo is failing.

FYI: We added an identical [.github/workflows/codeql.yml to the dbg repo](https://github.com/lcn2/dbg/blob/master/.github/workflows/codeql.yml) to the [dbg repo](https://github.com/lcn2/dbg) and that works over there.

Perhaps for this repo, the [.github/workflows/codeql.yml](https://github.com/lcn2/dyn_array/blob/master/.github/workflows/codeql.yml)  fails because it seems to have the [dbg repo](https://github.com/lcn2/dbg) installed ahead of time somehow?

# UPDATE 0

We are attempting a fix with commit 8aafca64fd1fff88e917550fccff94d321d3dbfa, trying to pre-install dbg before codeql.yml Autobuild.

That worked!

BTW: We probably could have replaced the autobuild with must a compile, however that commit hack works so we guess that is OK too.

**Comment by xexyl** [comment]
Thanks! I was going to test it once it was merged but since I was leaving .. and indeed I had forgotten about the other library. 

Glad you got it sorted. I was going to do the other repo but looks like you did it instead. 

Question is did I forget any rules to add? I was in a rush. I will be able to check soonish.

**Comment by xexyl** [comment]
# RHEL 9 works!

FYI: after uninstalling the libraries under Rocky Linux 9.4 (which I believe is RHEL based .. not just RH), both `make release` and `make prep` work in the mkiocccentry repo! Well done and thanks!

**Comment by lcn2** [comment]
> # RHEL 9 works!
> 
> 
> 
> FYI: after uninstalling the libraries under Rocky Linux 9.4 (which I believe is RHEL based .. not just RH), both `make release` and `make prep` work in the mkiocccentry repo! Well done and thanks!
> 
> 
> 
> 

You're welcome

**Comment by xexyl** [comment]
> > # RHEL 9 works!
> > FYI: after uninstalling the libraries under Rocky Linux 9.4 (which I believe is RHEL based .. not just RH), both `make release` and `make prep` work in the mkiocccentry repo! Well done and thanks!
> 
> You're welcome

🐬🦈🐠🐟

Okay but why sharks? Because sharks are fish of course! That is at least one thing that Jaws got right! Of course you know that .. but still it just adds to the irony here.

A sad but funny story that I maybe should not say: I saw someone calling themselves 'Science Guy' claim that sharks and whales are basically the same species .. despite the fact that sharks are fish and whales are mammals.

**Pull request merged**
